60 create store button
hto-projects/autohack-idle pull request #74
Opened 2024-06-25 18:28 UTC by emadsu

I added a plain store button that doesn't go anywhere but it says that it's coming soon so give it a chance guys!

2024-06-25 19:27 UTC, MangoMagoCane commented
Make sure to merge with the lastest commit from main

2024-06-26 12:33 UTC, jvgusch requested changes
Everything looks great so far, but I think I'd like to actually see the functionality as described in #60 as opposed to the placeholder you have right now. Unless there's some conversation I missed where this button is holding up others, you have time to create the user info page as well. It doesn't have to be fully fledged, but it can at least display the same coming soon message you already have.

2024-06-26 12:33 UTC, jvgusch commented on frontend/src/game/scenes/MainMenu.ts
> +import { GameObjects, Scene } from "phaser";
Your Prettier settings might be messed up, it's changing things against the style the rest of the team is submitting. You might want to double-check it's working correctly.

2024-06-26 19:18 UTC, closed without merging

2024-06-26 19:18 UTC, josephmaxwellhyland commented
We will be refactoring these buttons